version: '3'

services:
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 182002amine#

  web: 
      build: .
      volumes:
        - .:/usr/src/app
      ports:
        - "8000:8000"
